### ISSUE TITLE
Can I use the E4 camera In this project?

### ISSUE THREAD

**Issue by xiaocainiao72865** [generalmotors/thermal-scanning-kiosk#1]
I want to use FLIR E4 to reproduce the project, but the program stuck in looking for the camera. How can I do ? Please help me!

**Comment by jcurrie1234** [comment]
@xiaocainiao72865 the code is intentionally restricted to use the FLIR-E8 XT due to agreements with FLIR. FLIR has required this program to use the FLIR-E8 as they have stated that the E6 and E4 are not appropriate for this type of application as they will not provide the accuracy and resolution required.

**Comment by xiaocainiao72865** [comment]
> @xiaocainiao72865 the code is intentionally restricted to use the FLIR-E8 XT due to agreements with FLIR. FLIR has required this program to use the FLIR-E8 as they have stated that the E6 and E4 are not appropriate for this type of application as they will not provide the accuracy and resolution required.

Thank you for your answer. But unfortunately, I only have a FLIR E4 camera. I want to understand FLIR's workflow through reproduce the project in the postgraduate study. How can I remove the restriction in the project?

**Comment by dantelope** [comment]
@jcurrie1234 from a purely educational standpoint could we provide this?

**Comment by jcurrie1234** [comment]
I'm sorry that I can't help with your project, but providing information to bypass the intentional controls of this software would violate our agreement with FLIR and would violate the Terms of Use of this software, which can be found in the README file.

"FLIR requires that the use of this App with a FLIR EST Camera or approved FLIR Device is intended for use only as a skin temperature measuring tool, and is not a medically-approved body temperature measurement device or a medical diagnostic tool.

This kiosk relies on a third-party thermal infrared camera to provide readings to the software. An appropriate camera must be selected and any instructions for the camera followed for proper functioning of the kiosk. FLIR has indicated that its E8 camera is generally suitable for skin temperature screening applications."

**Comment by xiaocainiao72865** [comment]
It is very sad to hear this news. This is a wonderful program in GitHub, but unfortunately I can’t reproduce it with my E4. Thank you again for your generous help.
